import re

with open("masjid-al-hijrah-63 ( idcloudhost - others 5 fitur - Idul Adha Qurban ).py", "r") as f:
    content = f.read()

# I need to update the frontend logic for LACAK and PEMBAGIAN
# For LACAK:
lacak_frontend = """
            <!-- Main Content Container -->
            <div id="lacak-container" class="bg-white rounded-3xl p-6 md:p-8 shadow-xl border border-gray-100 w-full max-w-xl mx-auto">
                <div id="lacak-form-section">
                    <div class="text-center py-6">
                        <i class="fas fa-qrcode text-5xl text-gray-300 mb-4"></i>
                        <h3 class="text-lg font-bold text-gray-800 mb-2">Lacak Hewan Qurban Anda</h3>
                        <p class="text-xs text-gray-500 mb-6">Masukkan PIN yang diberikan oleh panitia untuk melacak status hewan secara real-time.</p>
                        <form id="lacak-form" class="flex flex-col gap-3">
                            <input type="text" id="track-pin" required placeholder="Masukkan PIN 6 karakter" class="w-full bg-gray-50 border border-gray-200 rounded-xl p-4 text-center font-mono font-bold text-lg uppercase focus:border-[#D4A017] focus:ring-1 focus:ring-[#D4A017] tracking-widest">
                            <button type="submit" class="w-full bg-[#1B4332] text-white py-4 rounded-xl font-bold shadow-lg hover:bg-[#153426] transition text-sm">Lacak Sekarang</button>
                        </form>
                    </div>
                </div>

                <div id="lacak-error-section" class="hidden text-center py-6 border border-red-100 bg-red-50 rounded-2xl mb-6">
                    <div class="w-16 h-16 bg-red-100 text-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
                        <i class="fas fa-times text-3xl"></i>
                    </div>
                    <h3 class="text-xl font-bold text-gray-800 mb-2">Pencarian Gagal</h3>
                    <p class="text-sm text-gray-500 mb-6" id="lacak-error-text"></p>
                    <button onclick="resetLacak()" class="bg-[#1B4332] text-white px-6 py-2 rounded-xl font-bold text-sm shadow-md hover:bg-[#153426] transition">Coba Lagi</button>
                </div>

                <div id="lacak-result-section" class="hidden">
                    <div class="text-center mb-8 border-b border-gray-100 pb-6">
                        <div class="inline-flex items-center gap-2 bg-[#D4A017]/10 text-[#D4A017] px-4 py-2 rounded-full mb-3">
                            <i id="res-animal-icon" class="fas fa-cow"></i>
                            <span class="font-bold text-sm uppercase tracking-wider" id="res-animal-type"></span>
                        </div>
                        <h3 class="text-2xl font-bold text-gray-800" id="res-sohibul-name"></h3>
                    </div>

                    <div class="relative pl-6 space-y-8">
                        <div class="absolute left-[35px] top-4 bottom-4 w-1 bg-gray-100 rounded-full"></div>

                        <!-- Steps will be generated by JS -->
                        <div id="res-steps-container"></div>
                    </div>

                    <div class="mt-8 pt-6 border-t border-gray-100 text-center">
                        <button onclick="resetLacak()" class="bg-gray-100 text-gray-600 px-6 py-2 rounded-xl font-bold text-sm shadow-sm hover:bg-gray-200 transition">Cek PIN Lainnya</button>
                    </div>
                </div>
            </div>

            <script>
                document.getElementById('lacak-form').addEventListener('submit', async function(e) {
                    e.preventDefault();
                    const pin = document.getElementById('track-pin').value;
                    const btn = this.querySelector('button');
                    btn.disabled = true;
                    btn.innerText = 'Mencari...';

                    try {
                        const res = await fetch('/qurban/lacak', {
                            method: 'POST',
                            headers: {'Content-Type': 'application/json'},
                            body: JSON.stringify({pin: pin})
                        });
                        if(!res.ok) {
                            let errText = "Terjadi kesalahan sistem saat mencari data.";
                            try { const errJson = await res.json(); errText = errJson.error || errText; } catch(e) {}
                            throw new Error(errText);
                        }
                        const data = await res.json();

                        if(data.success) {
                            showLacakResult(data.data);
                        } else {
                            throw new Error(data.error || "PIN Tidak Ditemukan");
                        }
                    } catch(err) {
                        document.getElementById('lacak-form-section').classList.add('hidden');
                        document.getElementById('lacak-error-section').classList.remove('hidden');
                        document.getElementById('lacak-error-text').innerText = err.message;
                    } finally {
                        btn.disabled = false;
                        btn.innerText = 'Lacak Sekarang';
                    }
                });

                function resetLacak() {
                    document.getElementById('lacak-result-section').classList.add('hidden');
                    document.getElementById('lacak-error-section').classList.add('hidden');
                    document.getElementById('lacak-form-section').classList.remove('hidden');
                    document.getElementById('track-pin').value = '';
                }

                function showLacakResult(data) {
                    document.getElementById('lacak-form-section').classList.add('hidden');
                    document.getElementById('lacak-error-section').classList.add('hidden');
                    document.getElementById('lacak-result-section').classList.remove('hidden');

                    document.getElementById('res-animal-icon').className = data.animal_type === 'Sapi' ? 'fas fa-cow' : 'fas fa-sheep';
                    document.getElementById('res-animal-type').innerText = data.animal_type + ' No. ' + data.queue_number;
                    document.getElementById('res-sohibul-name').innerText = data.sohibul_name;

                    const statuses = [
                        {id: 'menunggu_giliran', label: 'Menunggu', desc: 'Hewan qurban sedang menunggu antrean pemotongan.', icon: 'fa-hourglass-half'},
                        {id: 'sedang_disembelih', label: 'Diproses', desc: 'Sedang dalam proses penyembelihan sesuai syariat.', icon: 'fa-cut'},
                        {id: 'proses_pencacahan', label: 'Pencacahan', desc: 'Daging sedang dicacah dan ditimbang.', icon: 'fa-balance-scale'},
                        {id: 'siap_diambil', label: 'Selesai', desc: 'Daging qurban siap didistribusikan.', icon: 'fa-box-open'}
                    ];

                    let activeIdx = statuses.findIndex(s => s.id === data.status);
                    if(activeIdx === -1) activeIdx = 0;

                    const stepsHtml = statuses.map((s, idx) => {
                        let statusColor = 'gray-300';
                        let iconBg = 'bg-white border-2 border-gray-200 text-gray-300';
                        if(idx < activeIdx) {
                            statusColor = '#1B4332';
                            iconBg = 'bg-[#1B4332] text-white border-2 border-[#1B4332]';
                        } else if (idx === activeIdx) {
                            statusColor = '#D4A017';
                            iconBg = 'bg-[#D4A017] text-white border-4 border-white shadow-[0_0_0_2px_#D4A017] animate-pulse';
                        }

                        return `
                        <div class="flex items-start gap-4 relative z-10">
                            <div class="w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 mt-1 ${iconBg} transition-all duration-500">
                                <i class="fas ${s.icon}"></i>
                            </div>
                            <div class="bg-white p-4 rounded-2xl shadow-sm border border-gray-100 flex-1 ${idx === activeIdx ? 'ring-1 ring-[#D4A017]' : ''}">
                                <h4 class="font-bold text-[${statusColor}]">${idx+1}. ${s.label}</h4>
                                <p class="text-xs text-gray-500 mt-1">${s.desc}</p>
                            </div>
                        </div>
                        `;
                    }).join('');

                    document.getElementById('res-steps-container').innerHTML = stepsHtml;
                }
            </script>
"""

# Replace the Jinja conditionals in IDUL_ADHA_LACAK_HTML
lacak_html_part = re.search(r"IDUL_ADHA_LACAK_HTML = '''(.*?)'''\s*IDUL_ADHA_PEMBAGIAN_CEK_HTML", content, re.DOTALL).group(1)
new_lacak_html = re.sub(r"{% if error %}.*?{% endif %}", lacak_frontend.strip(), lacak_html_part, flags=re.DOTALL)
content = content.replace(lacak_html_part, new_lacak_html)


pembagian_frontend = """
            <div id="pembagian-form-section">
                <div class="text-center mb-6">
                    <p class="text-sm text-gray-600">Hindari antrean panjang. Cek jadwal pengambilan daging qurban RT Anda di sini.</p>
                </div>
                <form id="pembagian-form" class="space-y-4">
                    <div>
                        <label class="block text-xs font-bold text-gray-600 mb-1">NIK (Nomor Induk Kependudukan)</label>
                        <input type="text" id="cek_nik" required pattern="[0-9]{16}" title="Masukkan 16 digit angka NIK" placeholder="Contoh: 6472010000000001" class="w-full bg-gray-50 border border-gray-200 rounded-xl p-4 text-sm font-mono focus:border-[#D4A017] focus:ring-1 focus:ring-[#D4A017] tracking-widest text-center">
                    </div>

                    <div>
                        <label class="block text-xs font-bold text-gray-600 mb-1">Nomor Kupon (2FA)</label>
                        <input type="text" id="cek_kupon" required placeholder="Sesuai yang diberikan RT" class="w-full bg-gray-50 border border-gray-200 rounded-xl p-4 text-sm font-mono focus:border-[#D4A017] focus:ring-1 focus:ring-[#D4A017] tracking-widest text-center uppercase">
                    </div>

                    <button type="submit" class="w-full bg-[#1B4332] text-white py-4 rounded-xl font-bold shadow-lg hover:bg-[#153426] transition mt-2">Cek Jadwal Saya</button>
                </form>
            </div>

            <div id="pembagian-error-section" class="hidden text-center py-6 border border-red-100 bg-red-50 rounded-2xl mb-6 mt-4">
                <div class="w-16 h-16 bg-red-100 text-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
                    <i class="fas fa-exclamation-triangle text-3xl"></i>
                </div>
                <h3 class="text-xl font-bold text-gray-800 mb-2">Gagal Memuat Jadwal</h3>
                <p class="text-sm text-gray-500 mb-6" id="pembagian-error-text"></p>
                <button onclick="resetPembagian()" class="bg-[#1B4332] text-white px-6 py-2 rounded-xl font-bold text-sm shadow-md hover:bg-[#153426] transition">Coba Lagi</button>
            </div>

            <div id="pembagian-result-section" class="hidden">
                <div class="text-center mb-6">
                    <div class="w-16 h-16 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto mb-4 shadow-inner border border-green-200">
                        <i class="fas fa-check text-3xl"></i>
                    </div>
                    <h3 class="text-2xl font-bold text-[#1B4332] mb-1">Kupon Valid</h3>
                    <p class="text-sm text-gray-500">Silakan ambil paket qurban Anda sesuai jadwal di bawah ini.</p>
                </div>

                <div class="bg-gray-50 border border-gray-200 rounded-2xl p-6 text-center shadow-inner">
                    <p class="text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Identitas (Sesuai NIK)</p>
                    <p class="text-lg font-bold text-gray-800 mb-6" id="res-kupon-nik"></p>

                    <p class="text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Waktu & Sesi Pengambilan (<span id="res-kupon-rt"></span>)</p>
                    <p class="text-3xl font-mono font-bold text-[#D4A017] mb-6" id="res-kupon-time"></p>

                    <p class="text-xs text-gray-600 mb-1">Kupon: <strong class="font-mono text-gray-800" id="res-kupon-number"></strong></p>
                    <p class="text-xs text-gray-500">Status: <strong id="res-kupon-status" class="uppercase"></strong></p>
                </div>

                <div class="mt-6 text-center">
                    <button onclick="resetPembagian()" class="text-xs font-bold text-gray-500 hover:text-[#1B4332] transition">Cek NIK Lainnya</button>
                </div>
            </div>

            <script>
                document.getElementById('pembagian-form').addEventListener('submit', async function(e) {
                    e.preventDefault();
                    const nik = document.getElementById('cek_nik').value;
                    const kupon = document.getElementById('cek_kupon').value;
                    const btn = this.querySelector('button');
                    btn.disabled = true;
                    btn.innerText = 'Mengecek...';

                    try {
                        const res = await fetch('/qurban/pembagian/cek', {
                            method: 'POST',
                            headers: {'Content-Type': 'application/json'},
                            body: JSON.stringify({nik: nik, coupon_number: kupon})
                        });
                        if(!res.ok) {
                            let errText = "Terjadi kesalahan sistem saat mencari data.";
                            try { const errJson = await res.json(); errText = errJson.message || errText; } catch(e) {}
                            throw new Error(errText);
                        }
                        const data = await res.json();

                        if(data.found) {
                            showPembagianResult(data.data);
                        } else {
                            throw new Error(data.message || "Data tidak ditemukan. Silakan hubungi panitia.");
                        }
                    } catch(err) {
                        document.getElementById('pembagian-form-section').classList.add('hidden');
                        document.getElementById('pembagian-error-section').classList.remove('hidden');
                        document.getElementById('pembagian-error-text').innerText = err.message;
                    } finally {
                        btn.disabled = false;
                        btn.innerText = 'Cek Jadwal Saya';
                    }
                });

                function resetPembagian() {
                    document.getElementById('pembagian-result-section').classList.add('hidden');
                    document.getElementById('pembagian-error-section').classList.add('hidden');
                    document.getElementById('pembagian-form-section').classList.remove('hidden');
                    document.getElementById('cek_nik').value = '';
                    document.getElementById('cek_kupon').value = '';
                }

                function showPembagianResult(data) {
                    document.getElementById('pembagian-form-section').classList.add('hidden');
                    document.getElementById('pembagian-error-section').classList.add('hidden');
                    document.getElementById('pembagian-result-section').classList.remove('hidden');

                    document.getElementById('res-kupon-nik').innerText = data.nik.substring(0, 4) + '********' + data.nik.substring(12, 16);
                    document.getElementById('res-kupon-rt').innerText = data.rt_identifier;
                    document.getElementById('res-kupon-time').innerText = data.time_start + ' - ' + data.time_end;
                    document.getElementById('res-kupon-number').innerText = data.coupon_number;

                    const statEl = document.getElementById('res-kupon-status');
                    if(data.is_claimed) {
                        statEl.innerText = 'SUDAH DIAMBIL';
                        statEl.className = 'text-red-500 font-bold uppercase';
                    } else {
                        statEl.innerText = 'BELUM DIAMBIL';
                        statEl.className = 'text-green-500 font-bold uppercase';
                    }
                }
            </script>
"""

pembagian_html_part = re.search(r"IDUL_ADHA_PEMBAGIAN_CEK_HTML = '''(.*?)'''\s*IDUL_ADHA_PEMBAGIAN_ADMIN_HTML", content, re.DOTALL).group(1)
new_pembagian_html = re.sub(r"{% if error %}.*?{% endif %}", pembagian_frontend.strip(), pembagian_html_part, flags=re.DOTALL)
content = content.replace(pembagian_html_part, new_pembagian_html)


with open("masjid-al-hijrah-63 ( idcloudhost - others 5 fitur - Idul Adha Qurban ).py", "w") as f:
    f.write(content)
